AWSTemplateFormatVersion: '2010-09-09'
Description: 'Configuración de Grupos de Seguridad para AgroNet - 2025'

Parameters:
  EnvironmentName:
    Description: Nombre del entorno
    Type: String
    Default: prod

Resources:
  # Security Group para el ALB (Application Load Balancer)
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group para el Application Load Balancer
      VpcId: !ImportValue 
        Fn::Sub: "${EnvironmentName}-Main-VPC-ID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: Acceso HTTP desde Internet
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: Acceso HTTPS desde Internet
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-ALB-SG'

  # Security Group para las instancias Frontend
  FrontendInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group para las instancias Frontend
      VpcId: !ImportValue 
        Fn::Sub: "${EnvironmentName}-Main-VPC-ID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 4321
          ToPort: 4321
          SourceSecurityGroupId: !Ref ALBSecurityGroup
          Description: Acceso HTTP desde ALB
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: Acceso SSH para administracion
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-Frontend-Instance-SG'

  # Security Group para los NLBs (Network Load Balancers)
  NLBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group para los Network Load Balancers
      VpcId: !ImportValue 
        Fn::Sub: "${EnvironmentName}-Main-VPC-ID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId: !Ref FrontendInstanceSecurityGroup
          Description: Acceso HTTPS desde Frontend
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          SourceSecurityGroupId: !Ref FrontendInstanceSecurityGroup
          Description: Acceso HTTP desde Frontend
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-NLB-SG'

  # Security Group para las instancias Backend
  BackendInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group para las instancias Backend
      VpcId: !ImportValue 
        Fn::Sub: "${EnvironmentName}-Main-VPC-ID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          SourceSecurityGroupId: !Ref NLBSecurityGroup
          Description: Acceso desde NLBs
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: Acceso SSH para administracion
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-Backend-Instance-SG'

Outputs:
  ALBSecurityGroupId:
    Description: ID del Security Group del ALB
    Value: !Ref ALBSecurityGroup
    Export:
      Name: !Sub '${EnvironmentName}-ALB-SecurityGroup'

  FrontendInstanceSecurityGroupId:
    Description: ID del Security Group de instancias Frontend
    Value: !Ref FrontendInstanceSecurityGroup
    Export:
      Name: !Sub '${EnvironmentName}-Frontend-Instance-SecurityGroup'

  NLBSecurityGroupId:
    Description: ID del Security Group de los NLBs
    Value: !Ref NLBSecurityGroup
    Export:
      Name: !Sub '${EnvironmentName}-NLB-SecurityGroup'

  BackendInstanceSecurityGroupId:
    Description: ID del Security Group de instancias Backend
    Value: !Ref BackendInstanceSecurityGroup
    Export:
      Name: !Sub '${EnvironmentName}-Backend-Instance-SecurityGroup' 