AWSTemplateFormatVersion: '2010-09-09'
Description: 'Configuración de Grupos de Seguridad para AgroNet - 2025'

Parameters:
  EnvironmentName:
    Description: Nombre del entorno
    Type: String
    Default: prod

Resources:
  # Grupo de Seguridad para el ALB
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group para el Application Load Balancer
      VpcId: !ImportValue 
        Fn::Sub: "${EnvironmentName}-Frontend-VPC-ID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: Acceso HTTP desde Internet
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: Acceso HTTPS desde Internet
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-ALB-SG'

  # Grupo de Seguridad para instancias Frontend
  FrontendSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group para las instancias Frontend
      VpcId: !ImportValue 
        Fn::Sub: "${EnvironmentName}-Frontend-VPC-ID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSecurityGroup
          Description: Acceso HTTP desde ALB
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: Acceso SSH para administracion
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-Frontend-SG'

  # Grupo de Seguridad para los NLBs
  NLBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group para los Network Load Balancers
      VpcId: !ImportValue 
        Fn::Sub: "${EnvironmentName}-Frontend-VPC-ID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          SourceSecurityGroupId: !Ref FrontendSecurityGroup
          Description: Acceso desde Frontend a Backend
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-NLB-SG'

  # Grupo de Seguridad para instancias Backend
  BackendSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group para las instancias Backend
      VpcId: !ImportValue 
        Fn::Sub: "${EnvironmentName}-Backend-VPC-ID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: !ImportValue 
            Fn::Sub: "${EnvironmentName}-Frontend-VPC-CIDR"
          Description: Acceso desde NLBs
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: Acceso SSH para administracion
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-Backend-SG'

  # Regla para permitir que ALB acceda a Frontend
  ALBToFrontendEgress:
    Type: AWS::EC2::SecurityGroupEgress
    DependsOn: 
      - ALBSecurityGroup
      - FrontendSecurityGroup
    Properties:
      GroupId: !Ref ALBSecurityGroup
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      DestinationSecurityGroupId: !Ref FrontendSecurityGroup
      Description: Trafico desde ALB hacia Frontend

  # Regla para permitir que Frontend acceda a NLBs
  FrontendToNLBEgress:
    Type: AWS::EC2::SecurityGroupEgress
    DependsOn: 
      - FrontendSecurityGroup
      - NLBSecurityGroup
    Properties:
      GroupId: !Ref FrontendSecurityGroup
      IpProtocol: tcp
      FromPort: 3000
      ToPort: 3000
      DestinationSecurityGroupId: !Ref NLBSecurityGroup
      Description: Trafico desde Frontend hacia NLBs

Outputs:
  ALBSecurityGroupId:
    Description: ID del Security Group del ALB
    Value: !Ref ALBSecurityGroup
    Export:
      Name: !Sub '${EnvironmentName}-ALB-SecurityGroup'

  FrontendSecurityGroupId:
    Description: ID del Security Group de Frontend
    Value: !Ref FrontendSecurityGroup
    Export:
      Name: !Sub '${EnvironmentName}-Frontend-SecurityGroup'

  NLBSecurityGroupId:
    Description: ID del Security Group de los NLBs
    Value: !Ref NLBSecurityGroup
    Export:
      Name: !Sub '${EnvironmentName}-NLB-SecurityGroup'

  BackendSecurityGroupId:
    Description: ID del Security Group de Backend
    Value: !Ref BackendSecurityGroup
    Export:
      Name: !Sub '${EnvironmentName}-Backend-SecurityGroup' 