AWSTemplateFormatVersion: '2010-09-09'
Description: 'Configuración de VPC  para AgroNet - 2025'

Parameters:
  EnvironmentName:
    Description: Nombre del entorno
    Type: String
    Default: prod
  
  VPCMainCIDR:
    Description: CIDR para la VPC principal
    Type: String
    Default: 10.0.0.0/16

  # Subredes públicas
  PublicSubnet1CIDR:
    Type: String
    Default: 10.0.0.0/24
    Description: CIDR para la primera subred pública

  PublicSubnet2CIDR:
    Type: String
    Default: 10.0.1.0/24
    Description: CIDR para la segunda subred pública

  PublicSubnet3CIDR:
    Type: String
    Default: 10.0.2.0/24
    Description: CIDR para la tercera subred pública

  # Subredes privadas para Backend
  BackendPrivateSubnet1CIDR:
    Type: String
    Default: 10.0.3.0/24
    Description: CIDR para la primera subred privada de Backend

  BackendPrivateSubnet2CIDR:
    Type: String
    Default: 10.0.4.0/24
    Description: CIDR para la segunda subred privada de Backend

  BackendPrivateSubnet3CIDR:
    Type: String
    Default: 10.0.5.0/24
    Description: CIDR para la tercera subred privada de Backend

Resources:
  # VPC Principal
  MainVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCMainCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-Main-VPC'

  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-IGW'

  # Attachment del Internet Gateway
  IGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MainVPC
      InternetGatewayId: !Ref InternetGateway

  # Subredes públicas
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MainVPC
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: !Ref PublicSubnet1CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-Public-Subnet-1'

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MainVPC
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: !Ref PublicSubnet2CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-Public-Subnet-2'

  PublicSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MainVPC
      AvailabilityZone: !Select [2, !GetAZs '']
      CidrBlock: !Ref PublicSubnet3CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-Public-Subnet-3'

  # Subredes privadas para Backend
  BackendPrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MainVPC
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: !Ref BackendPrivateSubnet1CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-Backend-Private-Subnet-1'

  BackendPrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MainVPC
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: !Ref BackendPrivateSubnet2CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-Backend-Private-Subnet-2'

  BackendPrivateSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MainVPC
      AvailabilityZone: !Select [2, !GetAZs '']
      CidrBlock: !Ref BackendPrivateSubnet3CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-Backend-Private-Subnet-3'

  # NAT Gateways y Elastic IPs (uno por zona de disponibilidad)
  EIP1:
    Type: AWS::EC2::EIP
    DependsOn: IGWAttachment
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-NAT-EIP-1'

  EIP2:
    Type: AWS::EC2::EIP
    DependsOn: IGWAttachment
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-NAT-EIP-2'

  EIP3:
    Type: AWS::EC2::EIP
    DependsOn: IGWAttachment
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-NAT-EIP-3'

  NATGateway1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt EIP1.AllocationId
      SubnetId: !Ref PublicSubnet1
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-NAT-GW-1'

  NATGateway2:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt EIP2.AllocationId
      SubnetId: !Ref PublicSubnet2
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-NAT-GW-2'

  NATGateway3:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt EIP3.AllocationId
      SubnetId: !Ref PublicSubnet3
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-NAT-GW-3'

  # Tabla de rutas para subredes públicas
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MainVPC
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-Public-RT'

  # Ruta a Internet para subredes públicas
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: IGWAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  # Asociaciones de tablas de rutas para subredes públicas
  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet2

  PublicSubnet3RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet3

  # Tablas de rutas para subredes privadas Backend
  BackendPrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MainVPC
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-Backend-Private-RT-1'

  BackendPrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MainVPC
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-Backend-Private-RT-2'

  BackendPrivateRouteTable3:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MainVPC
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-Backend-Private-RT-3'

  # Rutas a NAT Gateways para subredes privadas Backend
  BackendPrivateRoute1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref BackendPrivateRouteTable1
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway1

  BackendPrivateRoute2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref BackendPrivateRouteTable2
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway2

  BackendPrivateRoute3:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref BackendPrivateRouteTable3
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway3

  # Asociaciones de tablas de rutas para subredes privadas Backend
  BackendPrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref BackendPrivateRouteTable1
      SubnetId: !Ref BackendPrivateSubnet1

  BackendPrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref BackendPrivateRouteTable2
      SubnetId: !Ref BackendPrivateSubnet2

  BackendPrivateSubnet3RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref BackendPrivateRouteTable3
      SubnetId: !Ref BackendPrivateSubnet3

Outputs:
  VPCId:
    Description: ID de la VPC principal
    Value: !Ref MainVPC
    Export:
      Name: !Sub "${EnvironmentName}-Main-VPC-ID"

  VPCCIDR:
    Description: CIDR de la VPC principal
    Value: !Ref VPCMainCIDR
    Export:
      Name: !Sub "${EnvironmentName}-Main-VPC-CIDR"

  PublicRouteTableID:
    Description: ID de la tabla de rutas pública
    Value: !Ref PublicRouteTable
    Export:
      Name: !Sub "${EnvironmentName}-Public-RouteTable-ID"

  BackendPrivateRouteTable1ID:
    Description: ID de la tabla de rutas privada 1 de Backend
    Value: !Ref BackendPrivateRouteTable1
    Export:
      Name: !Sub "${EnvironmentName}-Backend-Private-RouteTable1-ID"

  BackendPrivateRouteTable2ID:
    Description: ID de la tabla de rutas privada 2 de Backend
    Value: !Ref BackendPrivateRouteTable2
    Export:
      Name: !Sub "${EnvironmentName}-Backend-Private-RouteTable2-ID"

  BackendPrivateRouteTable3ID:
    Description: ID de la tabla de rutas privada 3 de Backend
    Value: !Ref BackendPrivateRouteTable3
    Export:
      Name: !Sub "${EnvironmentName}-Backend-Private-RouteTable3-ID"

  PublicSubnet1ID:
    Description: ID de la primera subred pública
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub "${EnvironmentName}-Public-Subnet-1-ID"

  PublicSubnet2ID:
    Description: ID de la segunda subred pública
    Value: !Ref PublicSubnet2
    Export:
      Name: !Sub "${EnvironmentName}-Public-Subnet-2-ID"

  PublicSubnet3ID:
    Description: ID de la tercera subred pública
    Value: !Ref PublicSubnet3
    Export:
      Name: !Sub "${EnvironmentName}-Public-Subnet-3-ID"

  BackendPrivateSubnet1ID:
    Description: ID de la primera subred privada de Backend
    Value: !Ref BackendPrivateSubnet1
    Export:
      Name: !Sub "${EnvironmentName}-Backend-Private-Subnet-1-ID"

  BackendPrivateSubnet2ID:
    Description: ID de la segunda subred privada de Backend
    Value: !Ref BackendPrivateSubnet2
    Export:
      Name: !Sub "${EnvironmentName}-Backend-Private-Subnet-2-ID"

  BackendPrivateSubnet3ID:
    Description: ID de la tercera subred privada de Backend
    Value: !Ref BackendPrivateSubnet3
    Export:
      Name: !Sub "${EnvironmentName}-Backend-Private-Subnet-3-ID" 