AWSTemplateFormatVersion: '2010-09-09'
Description: 'Configuración de recursos de cómputo para Backend con Auto Scaling - AgroNet 2025'

Parameters:
  EnvironmentName:
    Description: Nombre del entorno
    Type: String
    Default: prod

  BackendInstanceType:
    Description: Tipo de instancia EC2 para Backend
    Type: String
    Default: t3.small
    AllowedValues:
      - t3.small
      - t3.medium
      - t3.large

  KeyName:
    Description: Nombre del Key Pair de EC2 para acceso SSH
    Type: AWS::EC2::KeyPair::KeyName

  LatestAmiId:
    Description: AMI para instancias de Backend
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64

  MongoDBConnectionString:
    Description: Connection string para MongoDB Atlas
    Type: String
    Default: "mongodb+srv://user:password@cluster.mongodb.net/agronet?retryWrites=true&w=majority"
    NoEcho: true

  GitHubToken:
    Description: GitHub fine-grained personal access token para acceder a repositorios
    Type: String
    Default: "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"
    NoEcho: true

  MinSize:
    Description: Número mínimo de instancias en Auto Scaling Group
    Type: Number
    Default: 1
    MinValue: 1

  MaxSize:
    Description: Número máximo de instancias en Auto Scaling Group
    Type: Number
    Default: 3
    MinValue: 1

  DesiredCapacity:
    Description: Capacidad deseada para cada Auto Scaling Group
    Type: Number
    Default: 2
    MinValue: 1

Resources:
  # IAM Role para permitir a las instancias obtener acceso a S3, DynamoDB, etc
  BackendInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Policies:
        - PolicyName: !Sub ${EnvironmentName}-backend-instance-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - secretsmanager:GetSecretValue
                Resource: '*'

  BackendInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref BackendInstanceRole

  # Secret para almacenar el token de GitHub (si no existe ya)
  GitHubTokenSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${EnvironmentName}-github-token"
      Description: GitHub fine-grained personal access token
      SecretString: !Ref GitHubToken

  # CloudWatch Agent Configuration
  CloudWatchAgentConfig:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${EnvironmentName}/backend/cloudwatch-agent-config"
      Type: String
      Value: !Sub |
        {
          "agent": {
            "metrics_collection_interval": 60,
            "run_as_user": "root"
          },
          "metrics": {
            "append_dimensions": {
              "InstanceId": "${!aws:InstanceId}",
              "InstanceType": "${!aws:InstanceType}",
              "AutoScalingGroupName": "${!aws:AutoScalingGroupName}"
            },
            "metrics_collected": {
              "cpu": {
                "measurement": [
                  "cpu_usage_idle",
                  "cpu_usage_iowait",
                  "cpu_usage_user",
                  "cpu_usage_system"
                ],
                "metrics_collection_interval": 60,
                "totalcpu": true
              },
              "disk": {
                "measurement": [
                  "used_percent",
                  "inodes_free"
                ],
                "metrics_collection_interval": 60,
                "resources": [
                  "*"
                ]
              },
              "diskio": {
                "measurement": [
                  "io_time"
                ],
                "metrics_collection_interval": 60,
                "resources": [
                  "*"
                ]
              },
              "mem": {
                "measurement": [
                  "mem_used_percent"
                ],
                "metrics_collection_interval": 60
              },
              "swap": {
                "measurement": [
                  "swap_used_percent"
                ],
                "metrics_collection_interval": 60
              }
            }
          }
        }

  # Launch Templates para Backend
  BackendLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${EnvironmentName}-backend-launch-template
      VersionDescription: Initial version
      LaunchTemplateData:
        ImageId: !Ref LatestAmiId
        InstanceType: !Ref BackendInstanceType
        KeyName: !Ref KeyName
        SecurityGroupIds:
          - !ImportValue 
            Fn::Sub: "${EnvironmentName}-Backend-SecurityGroup"
        IamInstanceProfile:
          Name: !Ref BackendInstanceProfile
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash -xe
            # Configuración para Amazon Linux 2023
            # Esperar a tener conexión con los repositorios antes de continuar
            attempts=0
            max_attempts=5
            
            until dnf list installed &> /dev/null || [ $attempts -eq $max_attempts ]
            do
              echo "Intento $((attempts+1))/$max_attempts para conectar con repositorios..."
              sleep 10
              attempts=$((attempts+1))
            done
            
            if [ $attempts -eq $max_attempts ]; then
              echo "No se pudo conectar con los repositorios. Continuando con la instalación sin actualizar."
            else
              dnf update -y
            fi
            
            # Instalar dependencias necesarias
            dnf install -y git nodejs npm jq aws-cli wget libcap

            # Permitir que Node.js se vincule a puertos privilegiados sin ser root
            setcap 'cap_net_bind_service=+ep' $(which node)
            setcap 'cap_net_bind_service=+ep' /usr/bin/node-18

            # Instalar PM2 globalmente para gestionar el proceso
            npm install -g pm2

            # Instalar el agente de CloudWatch
            wget https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm
            rpm -U amazon-cloudwatch-agent.rpm
            
            # Configurar el agente de CloudWatch desde SSM Parameter Store
            aws ssm get-parameter --name "/${EnvironmentName}/backend/cloudwatch-agent-config" --region ${AWS::Region} --query "Parameter.Value" --output text > /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
            
            # Iniciar el agente de CloudWatch
            /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json

            # Obtener el token de GitHub desde Secrets Manager
            GITHUB_TOKEN=$(aws secretsmanager get-secret-value \
              --secret-id ${EnvironmentName}-github-token \
              --region ${AWS::Region} \
              --query SecretString --output text)

            # Configurar credenciales de Git para clonar repositorio
            echo "Configurando credenciales de Git..."
            export HOME=/home/ec2-user
            git config --global credential.helper store
            echo "https://oauth2:$GITHUB_TOKEN@github.com" > /home/ec2-user/.git-credentials
            chown ec2-user:ec2-user /home/ec2-user/.git-credentials
            chmod 600 /home/ec2-user/.git-credentials

            # Instalar dependencias y configurar
            cd /home/ec2-user
            echo "Clonando repositorio con token..."
            # Usar autenticación con token para clonar el repositorio
            sudo -u ec2-user git clone https://oauth2:$GITHUB_TOKEN@github.com/STW-24-25/Backend.git
            cd Backend
            sudo -u ec2-user npm install

            # Configurar variables de entorno
            cat > .env << EOL
            PORT=80
            NODE_ENV=production
            MONGODB_URI=${MongoDBConnectionString}
            JWT_SECRET=8b7932e4bb244a689bb47a1c7572582a
            AEMET_API_KEY=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZ3JvbmV0QGVqZW1wbG8uY29tIiwianRpIjoiMTM0MjNhYzktNTIzYi00YzFkLThkMjYtOWVhZWIzYTljZTIzIiwiaXNzIjoiQUVNRVQiLCJpYXQiOjE3MTM3OTk5NzksInVzZXJJZCI6IjEzNDIzYWM5LTUyM2ItNGMxZC04ZDI2LTllYWViM2E5Y2UyMyIsInJvbGUiOiIifQ.Dau0-Z6Qk_G7cSQR9UHKHvMc_uxrI_awz-xvYFtL_50
            EOL

            # Construir la aplicación
            sudo -u ec2-user npm run build
            
            # Iniciar con PM2 como usuario ec2-user
            sudo -u ec2-user pm2 start npm --name "backend" -- run start
            
            # Configurar PM2 para iniciar con el sistema
            pm2 startup -u ec2-user
            env PATH=$PATH:/usr/bin pm2 startup systemd -u ec2-user --hp /home/ec2-user
            sudo -u ec2-user pm2 save
            
            # Crear un script para ver los logs fácilmente
            cat > /usr/local/bin/check-logs << 'EOL'
              #!/bin/bash
              # Script para facilitar la revisión de logs
              echo "===== PM2 Status ====="
              su - ec2-user -c "pm2 status"
              echo ""
              echo "===== Backend Logs ====="
              echo "Últimas 50 líneas del log de salida:"
              tail -n 50 /home/ec2-user/.pm2/logs/backend-out.log
              echo ""
              echo "Últimas 50 líneas del log de error:"
              tail -n 50 /home/ec2-user/.pm2/logs/backend-error.log
            EOL
            chmod +x /usr/local/bin/check-logs
            
            # Limpiar credenciales después del despliegue
            rm /home/ec2-user/.git-credentials
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub ${EnvironmentName}-Backend-Instance
              - Key: Environment
                Value: !Ref EnvironmentName

  # Auto Scaling Groups para Backend en diferentes zonas
  BackendASG1:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub ${EnvironmentName}-Backend-ASG-1
      LaunchTemplate:
        LaunchTemplateId: !Ref BackendLaunchTemplate
        Version: !GetAtt BackendLaunchTemplate.LatestVersionNumber
      MinSize: !Ref MinSize
      MaxSize: !Ref MaxSize
      DesiredCapacity: !Ref DesiredCapacity
      VPCZoneIdentifier:
        - !ImportValue 
          Fn::Sub: "${EnvironmentName}-Backend-Private-Subnet-1-ID"
      TargetGroupARNs:
        - !ImportValue 
          Fn::Sub: "${EnvironmentName}-Backend-TG1-ARN"
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-Backend-ASG-1
          PropagateAtLaunch: true

  BackendASG2:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub ${EnvironmentName}-Backend-ASG-2
      LaunchTemplate:
        LaunchTemplateId: !Ref BackendLaunchTemplate
        Version: !GetAtt BackendLaunchTemplate.LatestVersionNumber
      MinSize: !Ref MinSize
      MaxSize: !Ref MaxSize
      DesiredCapacity: !Ref DesiredCapacity
      VPCZoneIdentifier:
        - !ImportValue 
          Fn::Sub: "${EnvironmentName}-Backend-Private-Subnet-2-ID"
      TargetGroupARNs:
        - !ImportValue 
          Fn::Sub: "${EnvironmentName}-Backend-TG2-ARN"
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-Backend-ASG-2
          PropagateAtLaunch: true

  BackendASG3:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub ${EnvironmentName}-Backend-ASG-3
      LaunchTemplate:
        LaunchTemplateId: !Ref BackendLaunchTemplate
        Version: !GetAtt BackendLaunchTemplate.LatestVersionNumber
      MinSize: !Ref MinSize
      MaxSize: !Ref MaxSize
      DesiredCapacity: !Ref DesiredCapacity
      VPCZoneIdentifier:
        - !ImportValue 
          Fn::Sub: "${EnvironmentName}-Backend-Private-Subnet-3-ID"
      TargetGroupARNs:
        - !ImportValue 
          Fn::Sub: "${EnvironmentName}-Backend-TG3-ARN"
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-Backend-ASG-3
          PropagateAtLaunch: true

  # Alarmas de CloudWatch para monitorizar CPU
  HighCPUAlarm1:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${EnvironmentName}-Backend-ASG1-HighCPU"
      AlarmDescription: "Alarma por alto uso de CPU en Backend ASG1"
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref BackendASG1
      AlarmActions:
        - !Ref BackendScaleOutPolicy1

  HighCPUAlarm2:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${EnvironmentName}-Backend-ASG2-HighCPU"
      AlarmDescription: "Alarma por alto uso de CPU en Backend ASG2"
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref BackendASG2
      AlarmActions:
        - !Ref BackendScaleOutPolicy2

  HighCPUAlarm3:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${EnvironmentName}-Backend-ASG3-HighCPU"
      AlarmDescription: "Alarma por alto uso de CPU en Backend ASG3"
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref BackendASG3
      AlarmActions:
        - !Ref BackendScaleOutPolicy3

  # Políticas de Auto Scaling
  BackendScaleOutPolicy1:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref BackendASG1
      Cooldown: 300
      ScalingAdjustment: 1

  BackendScaleOutPolicy2:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref BackendASG2
      Cooldown: 300
      ScalingAdjustment: 1

  BackendScaleOutPolicy3:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref BackendASG3
      Cooldown: 300
      ScalingAdjustment: 1

Outputs:
  BackendLaunchTemplateId:
    Description: ID de la Launch Template del Backend
    Value: !Ref BackendLaunchTemplate
    Export:
      Name: !Sub "${EnvironmentName}-Backend-LaunchTemplate-ID"

  BackendASG1Name:
    Description: Nombre del ASG 1 de Backend
    Value: !Ref BackendASG1
    Export:
      Name: !Sub "${EnvironmentName}-Backend-ASG1-Name"

  BackendASG2Name:
    Description: Nombre del ASG 2 de Backend
    Value: !Ref BackendASG2
    Export:
      Name: !Sub "${EnvironmentName}-Backend-ASG2-Name"

  BackendASG3Name:
    Description: Nombre del ASG 3 de Backend
    Value: !Ref BackendASG3
    Export:
      Name: !Sub "${EnvironmentName}-Backend-ASG3-Name"
      
  GitHubTokenSecretArn:
    Description: ARN del secreto que almacena el token de GitHub
    Value: !Ref GitHubTokenSecret
    Export:
      Name: !Sub "${EnvironmentName}-GitHub-Token-Secret-ARN" 