AWSTemplateFormatVersion: '2010-09-09'
Description: 'Plantilla principal para la arquitectura de AgroNet - 2025'

Parameters:
  EnvironmentName:
    Description: Nombre del entorno
    Type: String
    Default: prod
  
  BucketName:
    Description: Nombre del bucket S3 donde se encuentran las plantillas
    Type: String
    Default: agronet-cloudformation-templates-XXXX
    
  KeyName:
    Description: Nombre del Key Pair de EC2 para acceso SSH
    Type: AWS::EC2::KeyPair::KeyName
    
  MongoDBConnectionString:
    Description: Connection string para MongoDB Atlas
    Type: String
    Default: "mongodb+srv://user:password@cluster.mongodb.net/agronet?retryWrites=true&w=majority"
    NoEcho: true
    
  GitHubToken:
    Description: GitHub fine-grained personal access token para acceder a repositorios
    Type: String
    Default: "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"
    NoEcho: true

  # Parámetros para las redes
  VPCFrontendCIDR:
    Description: CIDR para la VPC Frontend
    Type: String
    Default: 10.0.0.0/16

  VPCBackendCIDR:
    Description: CIDR para la VPC Backend
    Type: String
    Default: 10.1.0.0/16

  PublicSubnet1CIDRFrontend:
    Type: String
    Default: 10.0.0.0/24
    Description: CIDR para la primera subred pública de Frontend

  PublicSubnet2CIDRFrontend:
    Type: String
    Default: 10.0.1.0/24
    Description: CIDR para la segunda subred pública de Frontend

  PublicSubnet3CIDRFrontend:
    Type: String
    Default: 10.0.2.0/24
    Description: CIDR para la tercera subred pública de Frontend

  PrivateSubnet1CIDRFrontend:
    Type: String
    Default: 10.0.3.0/24
    Description: CIDR para la primera subred privada de Frontend

  PrivateSubnet2CIDRFrontend:
    Type: String
    Default: 10.0.4.0/24
    Description: CIDR para la segunda subred privada de Frontend

  PrivateSubnet3CIDRFrontend:
    Type: String
    Default: 10.0.5.0/24
    Description: CIDR para la tercera subred privada de Frontend

  PublicSubnet1CIDRBackend:
    Type: String
    Default: 10.1.0.0/24
    Description: CIDR para la primera subred pública de Backend

  PublicSubnet2CIDRBackend:
    Type: String
    Default: 10.1.1.0/24
    Description: CIDR para la segunda subred pública de Backend

  PublicSubnet3CIDRBackend:
    Type: String
    Default: 10.1.2.0/24
    Description: CIDR para la tercera subred pública de Backend

  PrivateSubnet1CIDRBackend:
    Type: String
    Default: 10.1.3.0/24
    Description: CIDR para la primera subred privada de Backend

  PrivateSubnet2CIDRBackend:
    Type: String
    Default: 10.1.4.0/24
    Description: CIDR para la segunda subred privada de Backend

  PrivateSubnet3CIDRBackend:
    Type: String
    Default: 10.1.5.0/24
    Description: CIDR para la tercera subred privada de Backend

  # Parámetros para el cómputo
  FrontendInstanceType:
    Description: Tipo de instancia EC2 para Frontend
    Type: String
    Default: t3.small
    AllowedValues:
      - t3.small
      - t3.medium
      - t3.large
  
  BackendInstanceType:
    Description: Tipo de instancia EC2 para Backend
    Type: String
    Default: t3.small
    AllowedValues:
      - t3.small
      - t3.medium
      - t3.large
  
  MinSize:
    Description: Número mínimo de instancias en Auto Scaling Group
    Type: Number
    Default: 1
    MinValue: 1

  MaxSize:
    Description: Número máximo de instancias en Auto Scaling Group
    Type: Number
    Default: 3
    MinValue: 1

  DesiredCapacity:
    Description: Capacidad deseada para cada Auto Scaling Group
    Type: Number
    Default: 2
    MinValue: 1

Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${BucketName}.s3.eu-north-1.amazonaws.com/prod/network/vpc.yml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VPCFrontendCIDR: !Ref VPCFrontendCIDR
        VPCBackendCIDR: !Ref VPCBackendCIDR
        PublicSubnet1CIDRFrontend: !Ref PublicSubnet1CIDRFrontend
        PublicSubnet2CIDRFrontend: !Ref PublicSubnet2CIDRFrontend
        PublicSubnet3CIDRFrontend: !Ref PublicSubnet3CIDRFrontend
        PrivateSubnet1CIDRFrontend: !Ref PrivateSubnet1CIDRFrontend
        PrivateSubnet2CIDRFrontend: !Ref PrivateSubnet2CIDRFrontend
        PrivateSubnet3CIDRFrontend: !Ref PrivateSubnet3CIDRFrontend
        PublicSubnet1CIDRBackend: !Ref PublicSubnet1CIDRBackend
        PublicSubnet2CIDRBackend: !Ref PublicSubnet2CIDRBackend
        PublicSubnet3CIDRBackend: !Ref PublicSubnet3CIDRBackend
        PrivateSubnet1CIDRBackend: !Ref PrivateSubnet1CIDRBackend
        PrivateSubnet2CIDRBackend: !Ref PrivateSubnet2CIDRBackend
        PrivateSubnet3CIDRBackend: !Ref PrivateSubnet3CIDRBackend

  SecurityStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkStack
    Properties:
      TemplateURL: !Sub 'https://${BucketName}.s3.eu-north-1.amazonaws.com/prod/security/security-groups.yml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName

  LoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - NetworkStack
      - SecurityStack
    Properties:
      TemplateURL: !Sub 'https://${BucketName}.s3.eu-north-1.amazonaws.com/prod/network/load-balancers.yml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName

  ComputeBackendStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - NetworkStack
      - SecurityStack
      - LoadBalancerStack
    Properties:
      TemplateURL: !Sub 'https://${BucketName}.s3.eu-north-1.amazonaws.com/prod/compute/backend-compute.yml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        KeyName: !Ref KeyName
        MongoDBConnectionString: !Ref MongoDBConnectionString
        GitHubToken: !Ref GitHubToken
        BackendInstanceType: !Ref BackendInstanceType
        MinSize: !Ref MinSize
        MaxSize: !Ref MaxSize
        DesiredCapacity: !Ref DesiredCapacity

  ComputeFrontendStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - NetworkStack
      - SecurityStack
      - LoadBalancerStack
    Properties:
      TemplateURL: !Sub 'https://${BucketName}.s3.eu-north-1.amazonaws.com/prod/compute/frontend-compute.yml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        KeyName: !Ref KeyName
        GitHubToken: !Ref GitHubToken
        FrontendInstanceType: !Ref FrontendInstanceType

Outputs:
  ALBDNSName:
    Description: DNS del Application Load Balancer principal
    Value: !GetAtt LoadBalancerStack.Outputs.ALBDNSName
    Export:
      Name: !Sub "${EnvironmentName}-ALB-DNS" 