#!/bin/sh
# Check if package.json has changed, suggest running npm install
if git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD | grep --quiet "package.json"; then
  echo "📦 Project dependencies have changed. Run 'npm install' to update."
fi 