name: Security Scanning

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:     # Allow manual triggering

jobs:
  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install libcrypto for MongoDB Memory Server
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates libssl1.1 || wget -q https://raw.githubusercontent.com/mongodb-js/libmongocrypt/master/install-dependencies/install-libssl-1-1.sh -O /tmp/install-libssl.sh && sudo chmod +x /tmp/install-libssl.sh && sudo /tmp/install-libssl.sh
      - name: Install dependencies
        run: npm ci
      
      - name: Run npm audit
        run: npm audit --audit-level=high
      
      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'AgroNET'
          path: '.'
          format: 'HTML'
          out: 'reports'
          args: >
            --enableRetired
      
      - name: Upload security reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: reports/
      
      - name: Check for vulnerabilities in your dependencies
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high 